version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1-stretch-browsers-legacy
        environment:
          IMAGE_NAME: "sameersbn/gitlab"

    steps:
      - checkout

      - setup_remote_docker:
          version: 18.03.1-ce

      - run:
          name: Docker info
          command: |
            docker version
            docker info


      - restore_cache:
          keys:
            - cache-{{ .Branch }}
          paths:
            - /tmp/cache/layers.tar

      - run:
          name: Loading docker cache
          command: |
            if [[ -f /tmp/cache/layers.tar ]]; then
              echo "Loading cache ..."
              docker load -i /tmp/cache/layers.tar
              docker image ls
            else
              echo "Couldn't find any caches"
            fi

      - run:
          name: Build docker image
          command: |
            docker build --cache-from=${IMAGE_NAME} -t ${IMAGE_NAME} -t ${IMAGE_NAME}:$(cat VERSION) .

      - run:
          name: Launching container for testing
          command: |
            docker-compose up -d
            sleep 10

      - run:
          name: Testing image
          command: |
            docker run --network container:$(docker-compose ps -q gitlab) \
              appropriate/curl --retry 12 --retry-delay 5 --retry-connrefused http://localhost/explore

      - run:
          name: Generate docker build image cache
          command: |
            mkdir -p /tmp/cache/
            docker save -o /tmp/cache/layers.tar ${IMAGE_NAME}

      - save_cache:
          key: cache-{{ .Branch }}-{{ epoch }}
          paths:
            - /tmp/cache/layers.tar

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
